spring.application.name=Dev
spring.datasource.url=jdbc:mysql://localhost:3306/advjava
spring.datasource.username=root
spring.datasource.password=root1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=kalpesh
spring.security.user.password=kalpesh123



server.port=8081

